version: 2
jobs:
  build:
    working_directory: ~/SVH
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: svh
          POSTGRES_DB: svh_prod
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            sudo pip install -r ./svh/requirements.txt
      - run:
          command: |
            mkdir ./svh/svh/settings_local/
            touch ./svh/svh/settings_local/__init__.py
            sed -i "s/'HOST': 'postgres'/'HOST': 'localhost'/g" ./svh/svh/settings.py
      - run:
          command: |
            python ./svh/manage.py test ./svh
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          command: |
            ssh $SSH_USER@$SSH_HOST "cd ./SVH && git checkout $CIRCLE_SHA1 && ./docker/deploy.sh"