# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200, unique=True)),
                ('format', models.CharField(choices=[(b'youtube', b'-c:v libx264 -c:a aac -strict experimental -b:a 192k')], default=0, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200, unique=True)),
                ('hash', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='videofile',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='svh.VideoFile'),
        ),
    ]
