# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='format',
            field=models.CharField(choices=[(b'youtube', b'-c:v libx264 -c:a aac -strict experimental -b:a 192k')], default=(b'youtube', b'-c:v libx264 -c:a aac -strict experimental -b:a 192k'), max_length=200),
        ),
    ]
