# Generated by Django 2.2 on 2019-04-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svh', '0005_auto_20190424_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='sizeBytes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='videosource',
            name='sizeBytes',
            field=models.IntegerField(null=True),
        ),
    ]
