# Generated by Django 2.2 on 2019-05-06 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svh', '0007_auto_20190426_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosource',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='svh.VideoFolder'),
        ),
    ]
