# Generated by Django 2.2 on 2019-05-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svh', '0008_videosource_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_seconds', models.IntegerField(null=True)),
                ('image', models.ImageField(upload_to='')),
                ('videofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svh.VideoFile')),
            ],
        ),
    ]
