# Generated by Django 2.2 on 2019-05-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svh', '0009_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preview',
            old_name='videofile',
            new_name='videosource',
        ),
        migrations.AddField(
            model_name='videofolder',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videosource',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='preview',
            name='image',
            field=models.ImageField(upload_to='previews'),
        ),
    ]
