# Generated by Django 2.2 on 2019-07-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svh', '0011_auto_20190615_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosource',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
