# Generated by Django 2.2 on 2019-08-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svh', '0012_videosource_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofolder',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
