# Generated by Django 2.2 on 2019-12-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svh', '0016_auto_20191021_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofolder',
            name='preview_path',
        ),
    ]
