# Generated by Django 2.2.13 on 2020-06-26 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svh', '0017_remove_videofolder_preview_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videofolder',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='fileId',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='format',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='source',
        ),
        migrations.RemoveField(
            model_name='videofolder',
            name='_name',
        ),
        migrations.RemoveField(
            model_name='videofolder',
            name='path',
        ),
        migrations.AddField(
            model_name='videofile',
            name='_name',
            field=models.CharField(db_column='name', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videofile',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='svh.VideoFolder'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='hash',
            field=models.CharField(default='2', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videofile',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videofile',
            name='sizeBytes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='sourceHash',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videofolder',
            name='name',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VideoSource',
        ),
    ]
