# Generated by Django 2.2.13 on 2020-06-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svh', '0018_auto_20200626_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofolder',
            name='path',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
