# Generated by Django 2.2.13 on 2020-06-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svh', '0019_videofolder_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofile',
            name='sizeBytes',
        ),
        migrations.AddField(
            model_name='videofile',
            name='format',
            field=models.CharField(default='source', max_length=255),
        ),
    ]
