version: '3.3'

services:

# Proxypass nginx server
  nginx:
    build:
      context: nginx
    volumes:
      - media:/www/svh/media/
      - static:/www/svh/static
    links:
      - uwsgi
    depends_on:
      - uwsgi
    restart: always
    ports:
      - 80:80
#    command: [nginx-debug, '-g', 'daemon off;']


# Python web server
  uwsgi:
    build:
      context: ../
      dockerfile: docker/uwsgi/Dockerfile
    volumes:
    - settings:/www/svh/svh/settings_local/
    - media:/www/svh/media/
    - static:/www/svh/static
    depends_on:
    - postgres
    links:
    - postgres
    restart: always
    ports:
    - 127.0.0.1:9001:9000


# Celery for long running background tasks
  celery:
    build:
      context: ..
      dockerfile: docker/celery/Dockerfile
    volumes:
      - settings:/www/svh/svh/settings_local/
      - media:/www/svh/media/
    depends_on:
      - postgres
    links:
      - postgres
    restart: always


# PostgreSQL database
  postgres:
    build:
      context: postgres
    volumes:
    - db_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - 127.0.0.1:5432:5432

# RabbitMQ for celery
  rabbit:
    image: rabbitmq
    volumes:
      - rabbit:/var/lib/rabbitmq
    restart: always
    ports:
      - 127.0.0.1:5672:5672

# Torrent service
  torrent:
    image: wernight/qbittorrent
    volumes:
      - media:/www/svh/media
      - torrents:/torrents
    restart: always
    ports:
      - 127.0.0.1:8080:8080
      - 6881:6881
      - 6881:6881/udp
      
# File service
  fileservice:
    build:
      context: ../
      dockerfile: docker/fileservice/Dockerfile
   # volumes:
    #- media:/www/svh/media/
    environment:
        DatabaseSettings__ConnectionString: Host=postgres;Port=5432;Database=svhFiles;Username=svh;
        RabbitSettings__Host: rabbit
    depends_on:
    - postgres
    links:
    - postgres
    restart: always
    ports:
    - 127.0.0.1:5000:80

volumes:
  db_data: {}
  media:
    driver: local
    driver_opts:
      type: none
      device: ${MEDIA_PATH}
      o: bind
  settings: {}
  rabbit: {}
  static: {}
  torrents: {}