version: '3.3'

services:

# Proxypass nginx server
  nginx:
    build:
      context: nginx
    volumes:
      - media:/www/svh/media/
      - static:/www/svh/static
      - sources:/www/svh/sources
    links:
      - uwsgi
    depends_on:
      - uwsgi
    restart: always
    ports:
      - 80:80


# Python web server
  uwsgi:
    build:
      context: ../
      dockerfile: docker/uwsgi/Dockerfile
    volumes:
    - settings:/www/svh/svh/settings_local/
    - media:/www/svh/media/
    - static:/www/svh/static
    - sources:/www/svh/sources
    depends_on:
    - postgres
    links:
    - postgres
    restart: always
    ports:
    - 127.0.0.1:9001:9000


# Celery for long running background tasks
  celery:
    build:
      context: ..
      dockerfile: docker/celery/Dockerfile
    volumes:
      - settings:/www/svh/svh/settings_local/
      - media:/www/svh/media/
    depends_on:
      - postgres
    links:
      - postgres
    restart: always


# PostgreSQL database
  postgres:
    build:
      context: postgres
    volumes:
    - db_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - 127.0.0.1:5432:5432

# RabbitMQ for celery
  rabbit:
    image: rabbitmq
    volumes:
      - rabbit:/var/lib/rabbitmq
    restart: always
    ports:
      - 127.0.0.1:5672:5672


volumes:
  db_data: {}
  media: {}
  sources_host:
    driver_opts:
      type: none
      device: "/www/svh/videosources"
      o: bind
  sources: {}
  settings: {}
  rabbit: {}
  static: {}
