version: '3.3'

services:
  uwsgi:
    build:
      context: ..
      dockerfile: docker/uwsgi/Dockerfile
    volumes:
    - settings:/www/svh/svh/settings_local/
    - media:/www/svh/media/
    - sources:/www/svh/sources
    depends_on:
    - postgres
    links:
    - postgres
    restart: always
    ports:
    - 8000:8000

  postgres:
    build:
      context: postgres
      args: [MODULE]
    environment: [MODULE]
    volumes:
    - db_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - 127.0.0.1:5432:5432

  rabbit:
    image: rabbitmq
    volumes:
      - rabbit:/var/lib/rabbitmq
    restart: always
    ports:
      - 127.0.0.1:5672:5672

volumes:
  db_data: {}
  media: {}
  sources: {}
  settings: {}
  rabbit: {}

