version: '3.3'

services:
  nginx:
    build:
      context: nginx
    volumes:
      - media:/www/svh/media/
    links:
      - uwsgi
    depends_on:
      - uwsgi
    restart: always
    ports:
      - 80:80

  uwsgi:
    build:
      context: ../
      dockerfile: docker/uwsgi/Dockerfile
    volumes:
    - settings:/www/svh/svh/settings_local/
    - media:/www/svh/media/
    - ../../videosources:/www/svh/sources
    depends_on:
    - postgres
    links:
    - postgres
    restart: always
    ports:
    - 127.0.0.1:9001:9000

  celery:
    build:
      context: ..
      dockerfile: docker/celery/Dockerfile
    volumes:
      - settings:/www/svh/svh/settings_local/
      - media:/www/svh/media/
    depends_on:
      - postgres
    links:
      - postgres
    restart: always

  postgres:
    build:
      context: postgres
    volumes:
    - db_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - 127.0.0.1:5432:5432

  rabbit:
    image: rabbitmq
    volumes:
      - rabbit:/var/lib/rabbitmq
    restart: always
    ports:
      - 127.0.0.1:5672:5672

  sftp:
    image: atmoz/sftp
    volumes:
      - ../../videosources:/home/svh/videosources
    restart: always
    ports:
      - "2222:22"
    command: svh:secretpassword:1001

volumes:
  db_data: {}
  media: {}
  sources: {}
  settings: {}
  rabbit: {}

