# Generated by Django 2.2 on 2019-04-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svh', '0002_auto_20181009_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosource',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='format',
            field=models.CharField(choices=[('default', '-vcodec libx264')], default=('default', '-vcodec libx264'), max_length=200),
        ),
    ]
