# Generated by Django 2.2 on 2019-08-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svh', '0013_videofolder_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofolder',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
