# Generated by Django 2.2 on 2019-08-27 17:04

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('svh', '0014_videofolder_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofolder',
            name='_name',
            field=models.CharField(blank=True, db_column='name', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='videofolder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videofolder',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='folder_parent', to='svh.VideoFolder'),
        ),
        migrations.AlterField(
            model_name='videofolder',
            name='preview_path',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='videofolder',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
