CREATE USER svh;
CREATE DATABASE svh OWNER svh;
GRANT ALL PRIVILEGES ON DATABASE svh TO svh;
CREATE DATABASE svh_prod OWNER svh;
GRANT ALL PRIVILEGES ON DATABASE svh_prod TO svh;
ALTER USER svh CREATEDB;
